# Generated by Django 4.2.6 on 2023-10-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.TextField(blank=True, max_length=100, null=True)),
                ('Language', models.CharField(blank=True, max_length=100, null=True)),
                ('Genre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
