# Generated by Django 4.2.6 on 2023-10-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Multi_name', models.TextField(blank=True, max_length=100, null=True)),
                ('Multi_lang', models.CharField(blank=True, max_length=100, null=True)),
                ('Multi_genre', models.CharField(blank=True, max_length=100, null=True)),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('About', models.TextField(blank=True, max_length=500, null=True)),
                ('Cast', models.TextField(blank=True, max_length=500, null=True)),
                ('File', models.FileField(blank=True, null=True, upload_to='Multimedia')),
            ],
        ),
    ]
