# Generated by Django 4.2.6 on 2023-10-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_multidb'),
    ]

    operations = [
        migrations.AddField(
            model_name='multidb',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
