# Generated by Django 4.2.6 on 2023-11-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_multidb_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MalTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('cast', models.CharField(blank=True, max_length=500, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='malayalam images')),
                ('vid', models.FileField(blank=True, null=True, upload_to='malayalam videos')),
            ],
        ),
    ]
