# Generated by Django 4.2.6 on 2023-11-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_commentmultdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmultdb',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
