# Generated by Django 4.2.6 on 2023-11-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0003_commentmultdb_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmultdb',
            name='time',
        ),
    ]
