# Generated by Django 4.2.6 on 2023-11-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0004_remove_commentmultdb_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentMultDb',
        ),
    ]
